---


- name: Ensure target hosts are reachable
  hosts: all
  gather_facts: false
  tasks:
    - name: Add host key to known_hosts
      ansible.builtin.known_hosts:
        path: "~/.ssh/known_hosts"
        name: 10.0.2.58
        key: "{{ lookup('pipe', 'ssh-keyscan -H 10.0.2.58') }}"


- name: Deploy myservice jar to microservice hosts
  hosts: private
  become: true
  serial: "{{ serial | default(1) }}"
  roles:
    - role: deploy_jar
